export const DiagnosticCodes = {
  INVALID_ACTION: 'GEN001',
  MISSING_TARGET: 'GEN002',
  REPOSITORY_OBJECT_NOT_FOUND: 'GEN003',
  NO_VALID_LOCATOR: 'GEN004',
  UNSUPPORTED_EMITTER_CAPABILITY: 'GEN005',
  EMISSION_FAILURE: 'GEN006',
  FORMAT_FAILURE: 'GEN007'
};
