[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "automation_studio"
version = "0.1.0"
authors = [
  { name="Automation Studio", email="support@automationstudio.dev" },
]
description = "Python Framework for Automation Studio"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[project.scripts]
automation-python-runner = "automation_studio.runner:main"
