import { RecorderAdapterContract } from '@automation-studio/types';
import { RawRecorderEvent } from '../events/raw_event';

export type RecorderEventHandler = (event: RawRecorderEvent) => void;

/**
 * Platform Recorder Adapter lifecycle and event emitting contract.
 */
export interface PlatformRecorderAdapter {
  /**
   * The capability contract defining what this adapter can do.
   */
  readonly contract: RecorderAdapterContract;

  /**
   * Initialize resources required for recording.
   */
  initialize(): Promise<void>;

  /**
   * Subscribe to raw events generated by this adapter.
   */
  onEvent(handler: RecorderEventHandler): void;

  /**
   * Start producing events.
   */
  start(): Promise<void>;

  /**
   * Pause producing events.
   */
  pause(): Promise<void>;

  /**
   * Resume producing events.
   */
  resume(): Promise<void>;

  /**
   * Stop producing events.
   */
  stop(): Promise<void>;

  /**
   * Dispose resources.
   */
  dispose(): Promise<void>;
}
