"""
Adapter Providers.
"""
from typing import Protocol, Any, List

class IInputProvider(Protocol):
    def click(self, x: int, y: int) -> None: ...
    def double_click(self, x: int, y: int) -> None: ...
    def move(self, x: int, y: int) -> None: ...
    def type_text(self, text: str) -> None: ...
    def press(self, key: str) -> None: ...
    def hotkey(self, keys: List[str]) -> None: ...

class IWindowProvider(Protocol):
    def find(self, title: str) -> str: ...
    def activate(self, window_id: str) -> None: ...
    def close(self, window_id: str) -> None: ...
    def wait(self, title: str, timeout_ms: int = 5000) -> str: ...
    def exists(self, title: str) -> bool: ...

class IProcessProvider(Protocol):
    def launch(self, path: str, args: str = "") -> str: ...
    def kill(self, process_id: str) -> None: ...
    def exists(self, process_id: str) -> bool: ...
    def get_process(self, process_id: str) -> Any: ...

class IClipboardProvider(Protocol):
    def get(self) -> str: ...
    def set(self, text: str) -> None: ...
    def clear(self) -> None: ...

class ICaptureProvider(Protocol):
    def screen(self) -> Any: ...
    def region(self, x: int, y: int, width: int, height: int) -> Any: ...

class IAccessibilityProvider(Protocol):
    def find_element(self, conditions: Any) -> Any: ...
    def invoke_pattern(self, element: Any, pattern: str) -> None: ...
